// @generated by sdd-lite
export function createRuntime() {
  const hooks = [];
  return {
    onReset(fn) {
      hooks.push(fn);
    },
    async resetEnv() {
      const toRun = hooks.splice(0, hooks.length);
      const errors = [];
      for (const fn of toRun) {
        try {
          await fn();
        } catch (err) {
          errors.push(err);
        }
      }
      if (errors.length) {
        console.warn("[SDD] resetEnv: hook errors", errors);
      }
    },
  };
}
